name: Deploy

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push ldapauth
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          tags: xway/ldapauth:latest
          push: ${{ github.ref == 'refs/heads/main' }}
          build-args: GIT_COMMIT=${{ github.sha }}
      -
        name: Notify webhook
        run: |
          curl -s -D - -H 'User-Agent: custom-github-deploy-webhook/0.01 (${{ github.sha }})' -X POST https://x-way.org/xh/ldapauth-reload
